name: flutter_settings_ui_example
description: Example project for this package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  flutter_settings_ui:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/settings.png